package spotify

var Regions = map[string]string{
	"global": "Global",
	"ad":     "Andorra",
	"ar":     "Argentina",
	"at":     "Austria",
	"au":     "Australia",
	"be":     "Belgium",
	"bg":     "Bulgaria",
	"bo":     "Bolivia",
	"br":     "Brazil",
	"ca":     "Canada",
	"ch":     "Switzerland",
	"cl":     "Chile",
	"co":     "Colombia",
	"cr":     "Costa Rica",
	"cy":     "Cyprus",
	"cz":     "Czech Republic",
	"de":     "Germany",
	"dk":     "Denmark",
	"do":     "Dominican Republic",
	"ec":     "Ecuador",
	"ee":     "Estonia",
	"es":     "Spain",
	"fi":     "Finland",
	"fr":     "France",
	"gb":     "United Kingdom",
	"gr":     "Greece",
	"gt":     "Guatemala",
	"hk":     "Hong Kong",
	"hn":     "Honduras",
	"hu":     "Hungary",
	"id":     "Indonesia",
	"ie":     "Ireland",
	"il":     "Israel",
	"in":     "India",
	"is":     "Iceland",
	"it":     "Italy",
	"jp":     "Japan",
	"lt":     "Lithuania",
	"lu":     "Luxembourg",
	"lv":     "Latvia",
	"mx":     "Mexico",
	"my":     "Malaysia",
	"ni":     "Nicaragua",
	"nl":     "Netherlands",
	"no":     "Norway",
	"nz":     "New Zealand",
	"pa":     "Panama",
	"pe":     "Peru",
	"ph":     "Philippines",
	"pl":     "Poland",
	"pt":     "Portugal",
	"py":     "Paraguay",
	"ro":     "Romania",
	"ru":     "Russian Federation",
	"se":     "Sweden",
	"sg":     "Singapore",
	"sk":     "Slovakia",
	"sv":     "El Salvador",
	"th":     "Thailand",
	"tr":     "Turkey",
	"tw":     "Taiwan",
	"ua":     "Ukraine",
	"us":     "United States",
	"uy":     "Uruguay",
	"vn":     "Viet Nam",
	"za":     "South Africa",
}
